### ISSUE TITLE
Please update to Analyzer 0.39.x

### ISSUE THREAD

**Issue by DenisShakinov** [aloisdeniel/flutter_sheet_localization#11]
First of all, thanks for this library, it saves us a lot of time and make our localization a lot more convenient.
Could you please update this library to analyzer 0.39.x? Since many other libraries have been already updated to (for example json_serializable) it causes a dependency unresolving.
If you don't have enough time to provide such an update, please let me know I can make a pull request.

**Comment by aloisdeniel** [comment]
I upgraded the dependency and published a new version 1.2.0 for the generator!

**Comment by Elias8** [comment]
Hey @aloisdeniel, could you please upgrade the `build_runner` and `analyzer` versions to the latest ones? And for the future, don't you think it is a good idea to use a range for versioning dependencies, something like this 
``` yaml
dependencies:
  analyzer: '>=0.39.0 < 1.0.0'
```
Thanks!
