### ISSUE TITLE
Doesn't regenerate file when change on Drive

### ISSUE THREAD

**Issue by RealBug** [aloisdeniel/flutter_sheet_localization#17]
Hi, thanks for this great library! I've got a problem when I want to regenerate the localizations with
`flutter packages pub run build_runner build`

Ouput:

> [INFO] Generating build script...
> [INFO] Generating build script completed, took 341ms
> 
> [INFO] Initializing inputs
> [INFO] Reading cached asset graph...
> [INFO] Reading cached asset graph completed, took 73ms
> 
> [INFO] Checking for updates since last build...
> [INFO] Checking for updates since last build completed, took 781ms
> 
> [INFO] Running build...
> [INFO] 1.1s elapsed, 0/5 actions completed.
> [INFO] 2.1s elapsed, 0/5 actions completed.
> [INFO] 6.0s elapsed, 0/5 actions completed.
> [INFO] 11.7s elapsed, 1/5 actions completed.
> [INFO] Running build completed, took 11.7s
> 
> [INFO] Caching finalized dependency graph...
> [INFO] Caching finalized dependency graph completed, took 45ms
> 
> [INFO] Succeeded after 11.8s with 0 outputs (5 actions)

The workaround I found is to change the DOCID, generate it and then rechange with the good one to regenerate one more time.

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.17.0, on Mac OS X 10.15.4 19E287, locale fr-FR)
[✓] Android Studio (version 3.6)

dev_dependencies:
  flutter_sheet_localization_generator: ^1.2.0
  build_runner: ^1.3.1
```
Thx

**Comment by shadowmanpat** [comment]
Hi, I had the same issue. I think it keeps cached file. So I run  flutter clean to delete it. But I have to get packages again

**Comment by aloisdeniel** [comment]
Yeah the caching strategy of build_runner makes it impossible to detect distant changes.

I introduced a `version` parameter for the annotation. This way you can force a new generation each time you increment that number.

`@SheetLocalization('<key>', '0', 1)` -> `@SheetLocalization('<key>', '0', 2)`
