### ISSUE TITLE
Can not install package

### ISSUE THREAD

**Issue by Jojoooo1** [aloisdeniel/flutter_sheet_localization#21]
Hi,

I am trying to install the package (as defined in README) but unfortunately i keep getting those errors:

`dart --version
Dart SDK version: 2.9.0 (stable) (Fri Jul 31 10:59:48 2020 +0200) on "linux_x64"`

`flutter --version                                                                                                              
Flutter 1.20.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 2ae34518b8 (6 days ago) • 2020-08-05 19:53:19 -0700
Engine • revision c8e3b94853
Tools • Dart 2.9.0`

flutter doctor                                                                                                                  
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.20.1, on Linux, locale en_US.UTF-8)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.47.3)
[✓] Connected device (1 available)

• No issues found!

`flutter packages pub run build_runner build `
Precompiling executable...
Precompiled build_runner:build_runner.
[INFO] Generating build script...
[INFO] Generating build script completed, took 283ms

[WARNING] Deleted previous snapshot due to missing asset graph.
[INFO] Creating build script snapshot......
[INFO] Creating build script snapshot... completed, took 10.5s

[INFO] Initializing inputs
[INFO] Building new asset graph...
[INFO] Building new asset graph completed, took 649ms

[INFO] Checking for unexpected pre-existing outputs....
[INFO] Checking for unexpected pre-existing outputs. completed, took 1ms

[INFO] Running build...
[INFO] Generating SDK summary...
[SEVERE] flutter_sheet_localization_generator:flutter_sheet_localization on lib/app/controller/home_controller.dart:

Bad state: Unexpected diagnostics:
/mnt/sdb/Android/flutter/bin/cache/dart-sdk/lib/core/uri.dart:3259:39 - Expected an identifier.
[SEVERE] flutter_sheet_localization_generator:flutter_sheet_localization on lib/app/controller/home_controller.dart:

Bad state: Unexpected diagnostics:
/mnt/sdb/Android/flutter/bin/cache/dart-sdk/lib/core/uri.dart:3259:39 - Expected an identifier.
[SEVERE] flutter_sheet_localization_generator:flutter_sheet_localization on lib/app/controller/home_controller.dart:

Bad state: Unexpected diagnostics:
/mnt/sdb/Android/flutter/bin/cache/dart-sdk/lib/core/uri.dart:3259:39 - Expected an identifier.
[SEVERE] flutter_sheet_localization_generator:flutter_sheet_localization on lib/app/controller/home_controller.dart:

Bad state: Unexpected diagnostics:
/mnt/sdb/Android/flutter/bin/cache/dart-sdk/lib/core/uri.dart:3259:39 - Expected an identifier.
[SEVERE] flutter_sheet_localization_generator:flutter_sheet_localization on lib/app/controller/home_controller.dart:

Bad state: Unexpected diagnostics:
/mnt/sdb/Android/flutter/bin/cache/dart-sdk/lib/core/uri.dart:3259:39 - Expected an identifier.
[SEVERE] flutter_sheet_localization_generator:flutter_sheet_localization on lib/app/controller/home_controller.dart:

Bad state: Unexpected diagnostics:
/mnt/sdb/Android/flutter/bin/cache/dart-sdk/lib/core/uri.dart:3259:39 - Expected an identifier.
[SEVERE] flutter_sheet_localization_generator:flutter_sheet_localization on lib/app/controller/home_controller.dart:

Bad state: Unexpected diagnostics:
/mnt/sdb/Android/flutter/bin/cache/dart-sdk/lib/core/uri.dart:3259:39 - Expected an identifier.
[SEVERE] flutter_sheet_localization_generator:flutter_sheet_localization on lib/app/controller/home_controller.dart:

Bad state: Unexpected diagnostics:
/mnt/sdb/Android/flutter/bin/cache/dart-sdk/lib/core/uri.dart:3259:39 - Expected an identifier.
[SEVERE] flutter_sheet_localization_generator:flutter_sheet_localization on lib/app/controller/home_controller.dart:

Bad state: Unexpected diagnostics:
/mnt/sdb/Android/flutter/bin/cache/dart-sdk/lib/core/uri.dart:3259:39 - Expected an identifier.
[SEVERE] flutter_sheet_localization_generator:flutter_sheet_localization on lib/app/controller/home_controller.dart:

Bad state: Unexpected diagnostics:
/mnt/sdb/Android/flutter/bin/cache/dart-sdk/lib/core/uri.dart:3259:39 - Expected an identifier.
[SEVERE] flutter_sheet_localization_generator:flutter_sheet_localization on lib/app/controller/home_controller.dart:

Bad state: Unexpected diagnostics:
/mnt/sdb/Android/flutter/bin/cache/dart-sdk/lib/core/uri.dart:3259:39 - Expected an identifier.
[SEVERE] flutter_sheet_localization_generator:flutter_sheet_localization on lib/app/controller/home_controller.dart:

Bad state: Unexpected diagnostics:
/mnt/sdb/Android/flutter/bin/cache/dart-sdk/lib/core/uri.dart:3259:39 - Expected an identifier.
[SEVERE] flutter_sheet_localization_generator:flutter_sheet_localization on lib/app/controller/home_controller.dart:

Bad state: Unexpected diagnostics:
/mnt/sdb/Android/flutter/bin/cache/dart-sdk/lib/core/uri.dart:3259:39 - Expected an identifier.
[SEVERE] flutter_sheet_localization_generator:flutter_sheet_localization on lib/app/controller/home_controller.dart:

Bad state: Unexpected diagnostics:
/mnt/sdb/Android/flutter/bin/cache/dart-sdk/lib/core/uri.dart:3259:39 - Expected an identifier.
[SEVERE] flutter_sheet_localization_generator:flutter_sheet_localization on lib/app/controller/home_controller.dart:

Bad state: Unexpected diagnostics:
/mnt/sdb/Android/flutter/bin/cache/dart-sdk/lib/core/uri.dart:3259:39 - Expected an identifier.
[SEVERE] flutter_sheet_localization_generator:flutter_sheet_localization on lib/app/controller/home_controller.dart:

Bad state: Unexpected diagnostics:
/mnt/sdb/Android/flutter/bin/cache/dart-sdk/lib/core/uri.dart:3259:39 - Expected an identifier.
[SEVERE] flutter_sheet_localization_generator:flutter_sheet_localization on lib/app/controller/home_controller.dart:

**Comment by Jojoooo1** [comment]
Solved after adding:

dependency_overrides:
  analyzer: 0.39.14

**Comment by unboxme** [comment]
Same problem.

```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.20.2, on Mac OS X 10.15.5 19F101, locale en-RU)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Android Studio (version 4.0)
[!] VS Code (version 1.46.1)
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[✓] Connected device (2 available)

! Doctor found issues in 1 category.
```

**Comment by aloisdeniel** [comment]
Do you still have issues with the latest versions ?

**Comment by unboxme** [comment]
Everything works properly. I think the issue is solved.
