### ISSUE TITLE
Required import of intl package

### ISSUE THREAD

**Issue by illuminated** [aloisdeniel/flutter_sheet_localization#23]
FYI, I had to put an:
`import 'package:intl/intl.dart';`

in the `localizations.dart` in order to have `NumberFormat` and `DateFormat` recognized in the localizations.g.dart.

Without it I got errors in the ...g.dart file where dynamic values were being dealt with.

This is the error shown without importing the intl package:
<img width="961" alt="image" src="https://user-images.githubusercontent.com/295242/96200994-b0f1a880-0f5b-11eb-8661-2a510e0c424d.png">

**Comment by illuminated** [comment]
I have posted a double issue by error (first submission led me to an error page, so I wasn't aware it was posted). Please delete one of these, thanks.

**Comment by aloisdeniel** [comment]
Thanks for reporting !
