### ISSUE TITLE
put a column on whitelist for parsing

### ISSUE THREAD

**Issue by ArturAntin** [aloisdeniel/flutter_sheet_localization#26]
hey @aloisdeniel, I really like your work with this package. I'd have one suggestion: For better comprehensibility I'd love to add a group column in the google sheet. For example to group the keys by on which page they appear in my app. Of course you can just name your key `'<pageName>.<key>'`, nonetheless I think this would be a nice feature to just say somewhere that a specific column name should not be added as a language (same as the condition-column). Especially if you want to give the job to translate your app to someone without good it-skills it may be hard for them to read the sheet.
Thanks 😄

**Comment by aloisdeniel** [comment]
Hi ! So nice that it helped you!

The issue #27 could a first step to add comments. :)

**Comment by aloisdeniel** [comment]
Just added it in version 2.1.0.

Comment any column with `(<name>)` column name.
