### ISSUE TITLE
Comment out columns

### ISSUE THREAD

**Issue by guenth39** [aloisdeniel/flutter_sheet_localization#27]
Hey there,
your package relay helped us to make fast progress in internationalization of our app. What I really like is the possibility to just share the sheet and give it to someone else for translation. But what I'm missing is the possibility to have columns with custom data like description or further information for the translators. As well, I could imagine that it could be a cool feature to "comment out" columns to just remove that language in the next build. So, what is suggesting is to add a "comment out prefix". If the label of the column starts with that (for example `//`) the parser ignores that column. In that case, you can add as many custom columns as you want and remove languages temporary without any trouble.
Would love to see that feature in the package.
Are pull request welcome? If so, do you have any hint where to start? I think we could just remove the comment out columns from [fields](https://github.com/aloisdeniel/flutter_sheet_localization/blob/bafffd1011fa4cd2c76d2da9805f49519558b5db/flutter_sheet_localization_generator/lib/src/parser.dart#L34)?

**Comment by aloisdeniel** [comment]
Hi ! Glad it helped you out !

It seems like a great idea. :)

Since the sheet isn't used by technical people, `(<name>)` (parenthesis) may be more appropriate... maybe ?

It is pretty easy to implement, I'll add it very soon.

**Comment by aloisdeniel** [comment]
Just added it in version `2.1.0`.

**Comment by guenth39** [comment]
Wow! Thanks for the quick help!
