### ISSUE TITLE
inline styles

### ISSUE THREAD

**Issue by guenth39** [aloisdeniel/flutter_sheet_localization#37]
Is there any way to add support for inline styles like **bold** and _italic_ maybe with the Markdown syntax ** for bold and _ for italic? 
I often want to highlight a couple of words or for example the email address in a longer text. As of now, I have to add the part before and the part behind the variable as separate text parts and the text before and behind is often different on different languages, so it's quite complicated for others to helping out with translations.
And it would make the flutter code much cleaner because you don't need `RichText=>TextSpan=>[TextSpan(normal), TextSpan(bold), TextSpan(normal)]` anymore.

**Comment by aloisdeniel** [comment]
You can easily combine the label with [flutter_markdown](https://pub.dev/packages/flutter_markdown) to create formatted labels based on markdown syntax.

```dart
final labels = AppLocalizations.of(context);
print(labels.myLabel); // **Hello** world!
return MarkdownBody(labels.myLabel);
```
