### ISSUE TITLE
pluralisation 

### ISSUE THREAD

**Issue by joeblew99** [aloisdeniel/flutter_sheet_localization#4]
I have been using this. Its really a great idea.

Any chance we could have pluralisation ?

**Comment by aloisdeniel** [comment]
With latest version, you should be able to achieve this with **conditionals**.


### Conditionals

It is pretty common to have variants of a label based on a condition (for example: Genders, Plurals, ...).

Simply duplicate your entries and end them with `(<ConditionName>.<ConditionCase)`.


Example :

> | Key | fr | en |
> | --- | --- | --- |
> | example.man(Gender.male) | homme | man |
> | example.man(Gender.female) | femme | woman |

See [example](example) for more details.

#### Plurals

The conditionals can be used the same way for plurals :

Example :

> | Key | fr | en |
> | --- | --- | --- |
> | example.man(Plural.zero) | hommes |	man |
> | example.man(Plural.one) | homme | man |
> | example.man(Plural.multiple) | hommes | men |

From your Dart code, you can then define a function :

```dart
Plural plural(int count) {
  if (count == 0) return Plural.zero;
  if (count == 1) return Plural.one;
  return Plural.multiple;
}
```
