### ISSUE TITLE
Upgrading source_gen to 1.0.0 (null-safety)

### ISSUE THREAD

**Issue by dokinkon** [aloisdeniel/flutter_sheet_localization#44]
Thanks for this awesome library.

Could you please upgrade source_gen to 1.0.0? (which is null-safety)

Thanks

**Comment by aloisdeniel** [comment]
Sorry for the delay, I was on a big refactoring pass.

A new version is available. Please tell me if it works better on your side!

Note that there are a few changes to do to your delegate class implementation (see the README for more details).
