### ISSUE TITLE
Can you please upgarde to support dart 2.12 and null safe

### ISSUE THREAD

**Issue by uc-dve** [aloisdeniel/flutter_sheet_localization#45]

**Comment by mboe** [comment]
**YES** please

**Comment by stepanzalis** [comment]
it's already in PR #43

**Comment by aloisdeniel** [comment]
Sorry for the delay, I was on a refactoring pass.

A new version is available. Please tell me if it works better on your side!

Note that there are a few changes to do to your delegate class implementation (*see the README for more details*).
