### ISSUE TITLE
google translate the google sheet ?

### ISSUE THREAD

**Issue by winwisely99** [aloisdeniel/flutter_sheet_localization#7]
see mine: https://docs.google.com/spreadsheets/d/16eeYgh8dus50fISokKK8TMVWLR8A18Er-p5dBcO0FYw/edit#gid=0

The De column is machine translated.

But i am not sure how to turn the values into real values...
And hence remove the "=GOOGLETRANSLATE(C2,"en","de")"

any ideas ?

**Comment by spouletmathis** [comment]
CMD + C
CMD + MAJ + V

**Comment by aloisdeniel** [comment]
Sorry, I have no idea ... it is more a Google Sheet question.

In the meanwhile I would suggest you the  @spouletmathis solution : select the column and copy/paste it.

**Comment by winwisely99** [comment]
I got it working.

I used the ability of gsheets to publish to web as a CVS and then just pulled the CSV.
