### ISSUE TITLE
[WARNING] ... Missing "part 'localization.g.dart On MacOS Catalina (v10.15)

### ISSUE THREAD

**Issue by spouletmathis** [aloisdeniel/flutter_sheet_localization#8]
$ flutter packages pub run build_runner build
[INFO] Generating build script...
[INFO] Generating build script completed, took 509ms

[INFO] Initializing inputs
[INFO] Reading cached asset graph...
[INFO] Reading cached asset graph completed, took 118ms

[INFO] Checking for updates since last build...
[INFO] Checking for updates since last build completed, took 1.5s

[WARNING] glob|lib/src/io.dart was not found in the asset graph, incremental builds will not work.
 This probably means you don't have your dependencies specified fully in your pubspec.yaml.
[WARNING] Invalidating asset graph due to build script update!
[INFO] Cleaning up outputs from previous builds....
[INFO] Cleaning up outputs from previous builds. completed, took 6ms

[INFO] Generating build script...
[INFO] Generating build script completed, took 116ms

[INFO] Creating build script snapshot......
[INFO] Creating build script snapshot... completed, took 16.8s

[INFO] Initializing inputs
[INFO] Building new asset graph...
[INFO] Building new asset graph completed, took 963ms

[INFO] Checking for unexpected pre-existing outputs....
[INFO] Checking for unexpected pre-existing outputs. completed, took 2ms

[INFO] Running build...
[INFO] 1.2s elapsed, 1/16 actions completed.
[INFO] 2.3s elapsed, 6/22 actions completed.
[INFO] 3.4s elapsed, 6/22 actions completed.
[INFO] 4.8s elapsed, 8/24 actions completed.
[INFO] 5.9s elapsed, 11/27 actions completed.
[INFO] 9.8s elapsed, 11/27 actions completed.
[INFO] 14.6s elapsed, 17/32 actions completed.
[INFO] 15.6s elapsed, 27/40 actions completed.
[INFO] 16.9s elapsed, 40/42 actions completed.
[INFO] flutter_sheet_localization_generator:flutter_sheet_localization on lib/localization.dart:Downloading csv from Google sheet url "https://docs.google.com/spreadsheets/d/1TbuY592UMurrS2kmrW8GVPmHFGqnZ-SILtAZ7Hre10Y/export?format=csv&id=1TbuY592UMurrS2kmrW8GVPmHFGqnZ-SILtAZ7Hre10Y&gid=0" ...
[INFO] 18.0s elapsed, 41/42 actions completed.
**[WARNING] flutter_sheet_localization_generator:flutter_sheet_localization on lib/localization.dart:
Missing "part 'localization.g.dart';".**
[INFO] Running build completed, took 18.4s

[INFO] Caching finalized dependency graph...
[INFO] Caching finalized dependency graph completed, took 119ms

[INFO] Succeeded after 18.5s with 0 outputs (84 actions)

**Comment by spouletmathis** [comment]
[ a beginning of answer](https://medium.com/@nitishk72/flutter-and-macos-catalina-e32c5a6f373)

**Comment by aloisdeniel** [comment]
Thanks for reporting ! Do you still have issues with new releases of Flutter ?

**Comment by swaffoja** [comment]
I followed README.md explicitly and got the same error. The problem is that the readme instructs you to create a `lib/localization.dart` file with the provided contents. The provided contents in the readme has line `part 'localizations.g.dart';` that should be `part 'localization.g.dart';`. Just need to update the readme so file names match. I can submit a PR if I'm not clear.
